function write_touchstone(filename, freq, s11, s21, s12, s22)
%WRITE_TOUCHSTONE Write S-parameters to Touchstone format file
%
%   write_touchstone(filename, freq, s11, s21, s12, s22)
%
%   Writes 2-port S-parameters to a Touchstone (.s2p) file format
%   compatible with most RF simulation and measurement tools.
%
%   Inputs:
%       filename - Output filename (.s2p)
%       freq - Frequency vector in Hz
%       s11, s21, s12, s22 - Complex S-parameters
%
%   Author: Generated for Interdigital Bandpass Filter Project

    fid = fopen(filename, 'w');
    if fid == -1
        error('Cannot create touchstone file: %s', filename);
    end
    
    try
        % Write header
        fprintf(fid, '! Touchstone file generated by OpenEMS MATLAB interface\n');
        fprintf(fid, '! Date: %s\n', datestr(now));
        fprintf(fid, '! Format: Frequency(Hz) S11 S21 S12 S22\n');
        fprintf(fid, '# Hz S MA R 50\n');
        
        % Write S-parameter data
        for i = 1:length(freq)
            % Convert to magnitude and phase (degrees)
            s11_mag = abs(s11(i));
            s11_phase = angle(s11(i)) * 180/pi;
            s21_mag = abs(s21(i));
            s21_phase = angle(s21(i)) * 180/pi;
            s12_mag = abs(s12(i));
            s12_phase = angle(s12(i)) * 180/pi;
            s22_mag = abs(s22(i));
            s22_phase = angle(s22(i)) * 180/pi;
            
            fprintf(fid, '%.6e %.6e %.6e %.6e %.6e %.6e %.6e %.6e %.6e\n', ...
                    freq(i), s11_mag, s11_phase, s21_mag, s21_phase, ...
                    s12_mag, s12_phase, s22_mag, s22_phase);
        end
        
        fclose(fid);
        
    catch ME
        fclose(fid);
        rethrow(ME);
    end
    
    fprintf('Touchstone file written: %s\n', filename);
end